name: android static build scripts

on:
  workflow_dispatch:
    inputs:
      ndk_version:
        description: 'NDK Version'
        required: false
        default: 'r25b'
  push:
    branches:
      - development
      - main
    paths:
      - '.github/workflows/android-static-build-scripts.yml'
  pull_request:
    branches:
      - development
      - main
    paths:
      - '.github/workflows/android-static-build-scripts.yml'

jobs:
  build-android-static:
    name: android static libs (${{ matrix.arch }}, ${{ matrix.ndk-version }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ndk-version: [ 'r25b-linux' ]
        arch: [ 'arm64-v8a', 'x86_64' ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: set up adopt jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: set up android ndk
        run: |
          curl -s "https://dl.google.com/android/repository/android-ndk-${{ matrix.ndk-version }}.zip" -o ndk.zip
          unzip -q -o ndk.zip -d .ndk
          echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV

      - name: build with --no-archive
        run: |
          if [[ "${{ matrix.arch }}" == "arm64-v8a" ]]; then
            ./android.sh --no-archive --disable-x86 --disable-x86-64 --disable-arm-v7a --disable-arm-v7a-neon
          else
            ./android.sh --no-archive --disable-arm-v7a --disable-arm-v7a-neon --disable-arm64-v8a
          fi

      - name: print build logs
        if: ${{ always() }}
        run: cat build.log

      - name: upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-android-static-${{ matrix.arch }}-${{ matrix.ndk-version }}
          path: |
            prebuilt/**/lib/*.a
            prebuilt/**/include/**
          retention-days: 7
